// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: proto_test.proto

package me.vicasong.swagger.docgen.protocol;

public final class TestProtos {
  private TestProtos() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface BaseInfoMsgOrBuilder extends
      // @@protoc_insertion_point(interface_extends:BaseInfoMsg)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     * ID
     * </pre>
     *
     * <code>int32 id = 1;</code>
     */
    int getId();

    /**
     * <pre>
     * 姓名
     * </pre>
     *
     * <code>string name = 2;</code>
     */
    String getName();
    /**
     * <pre>
     * 姓名
     * </pre>
     *
     * <code>string name = 2;</code>
     */
    com.google.protobuf.ByteString
        getNameBytes();

    /**
     * <pre>
     * 时间戳
     * </pre>
     *
     * <code>int64 time = 3;</code>
     */
    long getTime();

    /**
     * <pre>
     * 性别
     * </pre>
     *
     * <code>.BaseInfoMsg.Gender gender = 4;</code>
     */
    int getGenderValue();
    /**
     * <pre>
     * 性别
     * </pre>
     *
     * <code>.BaseInfoMsg.Gender gender = 4;</code>
     */
    me.vicasong.swagger.docgen.protocol.TestProtos.BaseInfoMsg.Gender getGender();

    /**
     * <pre>
     * 地址
     * </pre>
     *
     * <code>string address = 5;</code>
     */
    String getAddress();
    /**
     * <pre>
     * 地址
     * </pre>
     *
     * <code>string address = 5;</code>
     */
    com.google.protobuf.ByteString
        getAddressBytes();
  }
  /**
   * <pre>
   * 基本信息
   * </pre>
   *
   * Protobuf type {@code BaseInfoMsg}
   */
  public  static final class BaseInfoMsg extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:BaseInfoMsg)
      BaseInfoMsgOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use BaseInfoMsg.newBuilder() to construct.
    private BaseInfoMsg(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private BaseInfoMsg() {
      id_ = 0;
      name_ = "";
      time_ = 0L;
      gender_ = 0;
      address_ = "";
    }

    @Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private BaseInfoMsg(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {

              id_ = input.readInt32();
              break;
            }
            case 18: {
              String s = input.readStringRequireUtf8();

              name_ = s;
              break;
            }
            case 24: {

              time_ = input.readInt64();
              break;
            }
            case 32: {
              int rawValue = input.readEnum();

              gender_ = rawValue;
              break;
            }
            case 42: {
              String s = input.readStringRequireUtf8();

              address_ = s;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return me.vicasong.swagger.docgen.protocol.TestProtos.internal_static_BaseInfoMsg_descriptor;
    }

    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return me.vicasong.swagger.docgen.protocol.TestProtos.internal_static_BaseInfoMsg_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              me.vicasong.swagger.docgen.protocol.TestProtos.BaseInfoMsg.class, me.vicasong.swagger.docgen.protocol.TestProtos.BaseInfoMsg.Builder.class);
    }

    /**
     * <pre>
     * 性别
     * </pre>
     *
     * Protobuf enum {@code BaseInfoMsg.Gender}
     */
    public enum Gender
        implements com.google.protobuf.ProtocolMessageEnum {
      /**
       * <pre>
       * 男
       * </pre>
       *
       * <code>MALE = 0;</code>
       */
      MALE(0),
      /**
       * <pre>
       * 女
       * </pre>
       *
       * <code>FEMALE = 1;</code>
       */
      FEMALE(1),
      UNRECOGNIZED(-1),
      ;

      /**
       * <pre>
       * 男
       * </pre>
       *
       * <code>MALE = 0;</code>
       */
      public static final int MALE_VALUE = 0;
      /**
       * <pre>
       * 女
       * </pre>
       *
       * <code>FEMALE = 1;</code>
       */
      public static final int FEMALE_VALUE = 1;


      public final int getNumber() {
        if (this == UNRECOGNIZED) {
          throw new IllegalArgumentException(
              "Can't get the number of an unknown enum value.");
        }
        return value;
      }

      /**
       * @deprecated Use {@link #forNumber(int)} instead.
       */
      @Deprecated
      public static Gender valueOf(int value) {
        return forNumber(value);
      }

      public static Gender forNumber(int value) {
        switch (value) {
          case 0: return MALE;
          case 1: return FEMALE;
          default: return null;
        }
      }

      public static com.google.protobuf.Internal.EnumLiteMap<Gender>
          internalGetValueMap() {
        return internalValueMap;
      }
      private static final com.google.protobuf.Internal.EnumLiteMap<
          Gender> internalValueMap =
            new com.google.protobuf.Internal.EnumLiteMap<Gender>() {
              public Gender findValueByNumber(int number) {
                return Gender.forNumber(number);
              }
            };

      public final com.google.protobuf.Descriptors.EnumValueDescriptor
          getValueDescriptor() {
        return getDescriptor().getValues().get(ordinal());
      }
      public final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptorForType() {
        return getDescriptor();
      }
      public static final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptor() {
        return me.vicasong.swagger.docgen.protocol.TestProtos.BaseInfoMsg.getDescriptor().getEnumTypes().get(0);
      }

      private static final Gender[] VALUES = values();

      public static Gender valueOf(
          com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
        if (desc.getType() != getDescriptor()) {
          throw new IllegalArgumentException(
            "EnumValueDescriptor is not for this type.");
        }
        if (desc.getIndex() == -1) {
          return UNRECOGNIZED;
        }
        return VALUES[desc.getIndex()];
      }

      private final int value;

      private Gender(int value) {
        this.value = value;
      }

      // @@protoc_insertion_point(enum_scope:BaseInfoMsg.Gender)
    }

    public static final int ID_FIELD_NUMBER = 1;
    private int id_;
    /**
     * <pre>
     * ID
     * </pre>
     *
     * <code>int32 id = 1;</code>
     */
    public int getId() {
      return id_;
    }

    public static final int NAME_FIELD_NUMBER = 2;
    private volatile Object name_;
    /**
     * <pre>
     * 姓名
     * </pre>
     *
     * <code>string name = 2;</code>
     */
    public String getName() {
      Object ref = name_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        name_ = s;
        return s;
      }
    }
    /**
     * <pre>
     * 姓名
     * </pre>
     *
     * <code>string name = 2;</code>
     */
    public com.google.protobuf.ByteString
        getNameBytes() {
      Object ref = name_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b =
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        name_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int TIME_FIELD_NUMBER = 3;
    private long time_;
    /**
     * <pre>
     * 时间戳
     * </pre>
     *
     * <code>int64 time = 3;</code>
     */
    public long getTime() {
      return time_;
    }

    public static final int GENDER_FIELD_NUMBER = 4;
    private int gender_;
    /**
     * <pre>
     * 性别
     * </pre>
     *
     * <code>.BaseInfoMsg.Gender gender = 4;</code>
     */
    public int getGenderValue() {
      return gender_;
    }
    /**
     * <pre>
     * 性别
     * </pre>
     *
     * <code>.BaseInfoMsg.Gender gender = 4;</code>
     */
    public me.vicasong.swagger.docgen.protocol.TestProtos.BaseInfoMsg.Gender getGender() {
      me.vicasong.swagger.docgen.protocol.TestProtos.BaseInfoMsg.Gender result = me.vicasong.swagger.docgen.protocol.TestProtos.BaseInfoMsg.Gender.valueOf(gender_);
      return result == null ? me.vicasong.swagger.docgen.protocol.TestProtos.BaseInfoMsg.Gender.UNRECOGNIZED : result;
    }

    public static final int ADDRESS_FIELD_NUMBER = 5;
    private volatile Object address_;
    /**
     * <pre>
     * 地址
     * </pre>
     *
     * <code>string address = 5;</code>
     */
    public String getAddress() {
      Object ref = address_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        address_ = s;
        return s;
      }
    }
    /**
     * <pre>
     * 地址
     * </pre>
     *
     * <code>string address = 5;</code>
     */
    public com.google.protobuf.ByteString
        getAddressBytes() {
      Object ref = address_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b =
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        address_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (id_ != 0) {
        output.writeInt32(1, id_);
      }
      if (!getNameBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, name_);
      }
      if (time_ != 0L) {
        output.writeInt64(3, time_);
      }
      if (gender_ != me.vicasong.swagger.docgen.protocol.TestProtos.BaseInfoMsg.Gender.MALE.getNumber()) {
        output.writeEnum(4, gender_);
      }
      if (!getAddressBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 5, address_);
      }
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (id_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, id_);
      }
      if (!getNameBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, name_);
      }
      if (time_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(3, time_);
      }
      if (gender_ != me.vicasong.swagger.docgen.protocol.TestProtos.BaseInfoMsg.Gender.MALE.getNumber()) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(4, gender_);
      }
      if (!getAddressBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(5, address_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @Override
    public boolean equals(final Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof me.vicasong.swagger.docgen.protocol.TestProtos.BaseInfoMsg)) {
        return super.equals(obj);
      }
      me.vicasong.swagger.docgen.protocol.TestProtos.BaseInfoMsg other = (me.vicasong.swagger.docgen.protocol.TestProtos.BaseInfoMsg) obj;

      boolean result = true;
      result = result && (getId()
          == other.getId());
      result = result && getName()
          .equals(other.getName());
      result = result && (getTime()
          == other.getTime());
      result = result && gender_ == other.gender_;
      result = result && getAddress()
          .equals(other.getAddress());
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + ID_FIELD_NUMBER;
      hash = (53 * hash) + getId();
      hash = (37 * hash) + NAME_FIELD_NUMBER;
      hash = (53 * hash) + getName().hashCode();
      hash = (37 * hash) + TIME_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getTime());
      hash = (37 * hash) + GENDER_FIELD_NUMBER;
      hash = (53 * hash) + gender_;
      hash = (37 * hash) + ADDRESS_FIELD_NUMBER;
      hash = (53 * hash) + getAddress().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static me.vicasong.swagger.docgen.protocol.TestProtos.BaseInfoMsg parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static me.vicasong.swagger.docgen.protocol.TestProtos.BaseInfoMsg parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static me.vicasong.swagger.docgen.protocol.TestProtos.BaseInfoMsg parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static me.vicasong.swagger.docgen.protocol.TestProtos.BaseInfoMsg parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static me.vicasong.swagger.docgen.protocol.TestProtos.BaseInfoMsg parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static me.vicasong.swagger.docgen.protocol.TestProtos.BaseInfoMsg parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static me.vicasong.swagger.docgen.protocol.TestProtos.BaseInfoMsg parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static me.vicasong.swagger.docgen.protocol.TestProtos.BaseInfoMsg parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static me.vicasong.swagger.docgen.protocol.TestProtos.BaseInfoMsg parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static me.vicasong.swagger.docgen.protocol.TestProtos.BaseInfoMsg parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static me.vicasong.swagger.docgen.protocol.TestProtos.BaseInfoMsg parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static me.vicasong.swagger.docgen.protocol.TestProtos.BaseInfoMsg parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(me.vicasong.swagger.docgen.protocol.TestProtos.BaseInfoMsg prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @Override
    protected Builder newBuilderForType(
        BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * <pre>
     * 基本信息
     * </pre>
     *
     * Protobuf type {@code BaseInfoMsg}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:BaseInfoMsg)
        me.vicasong.swagger.docgen.protocol.TestProtos.BaseInfoMsgOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return me.vicasong.swagger.docgen.protocol.TestProtos.internal_static_BaseInfoMsg_descriptor;
      }

      protected FieldAccessorTable
          internalGetFieldAccessorTable() {
        return me.vicasong.swagger.docgen.protocol.TestProtos.internal_static_BaseInfoMsg_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                me.vicasong.swagger.docgen.protocol.TestProtos.BaseInfoMsg.class, me.vicasong.swagger.docgen.protocol.TestProtos.BaseInfoMsg.Builder.class);
      }

      // Construct using me.vicasong.swagger.docgen.protocol.TestProtos.BaseInfoMsg.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        id_ = 0;

        name_ = "";

        time_ = 0L;

        gender_ = 0;

        address_ = "";

        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return me.vicasong.swagger.docgen.protocol.TestProtos.internal_static_BaseInfoMsg_descriptor;
      }

      public me.vicasong.swagger.docgen.protocol.TestProtos.BaseInfoMsg getDefaultInstanceForType() {
        return me.vicasong.swagger.docgen.protocol.TestProtos.BaseInfoMsg.getDefaultInstance();
      }

      public me.vicasong.swagger.docgen.protocol.TestProtos.BaseInfoMsg build() {
        me.vicasong.swagger.docgen.protocol.TestProtos.BaseInfoMsg result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public me.vicasong.swagger.docgen.protocol.TestProtos.BaseInfoMsg buildPartial() {
        me.vicasong.swagger.docgen.protocol.TestProtos.BaseInfoMsg result = new me.vicasong.swagger.docgen.protocol.TestProtos.BaseInfoMsg(this);
        result.id_ = id_;
        result.name_ = name_;
        result.time_ = time_;
        result.gender_ = gender_;
        result.address_ = address_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof me.vicasong.swagger.docgen.protocol.TestProtos.BaseInfoMsg) {
          return mergeFrom((me.vicasong.swagger.docgen.protocol.TestProtos.BaseInfoMsg)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(me.vicasong.swagger.docgen.protocol.TestProtos.BaseInfoMsg other) {
        if (other == me.vicasong.swagger.docgen.protocol.TestProtos.BaseInfoMsg.getDefaultInstance()) return this;
        if (other.getId() != 0) {
          setId(other.getId());
        }
        if (!other.getName().isEmpty()) {
          name_ = other.name_;
          onChanged();
        }
        if (other.getTime() != 0L) {
          setTime(other.getTime());
        }
        if (other.gender_ != 0) {
          setGenderValue(other.getGenderValue());
        }
        if (!other.getAddress().isEmpty()) {
          address_ = other.address_;
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        me.vicasong.swagger.docgen.protocol.TestProtos.BaseInfoMsg parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (me.vicasong.swagger.docgen.protocol.TestProtos.BaseInfoMsg) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private int id_ ;
      /**
       * <pre>
       * ID
       * </pre>
       *
       * <code>int32 id = 1;</code>
       */
      public int getId() {
        return id_;
      }
      /**
       * <pre>
       * ID
       * </pre>
       *
       * <code>int32 id = 1;</code>
       */
      public Builder setId(int value) {

        id_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * ID
       * </pre>
       *
       * <code>int32 id = 1;</code>
       */
      public Builder clearId() {

        id_ = 0;
        onChanged();
        return this;
      }

      private Object name_ = "";
      /**
       * <pre>
       * 姓名
       * </pre>
       *
       * <code>string name = 2;</code>
       */
      public String getName() {
        Object ref = name_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          name_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <pre>
       * 姓名
       * </pre>
       *
       * <code>string name = 2;</code>
       */
      public com.google.protobuf.ByteString
          getNameBytes() {
        Object ref = name_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b =
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          name_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       * 姓名
       * </pre>
       *
       * <code>string name = 2;</code>
       */
      public Builder setName(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }

        name_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 姓名
       * </pre>
       *
       * <code>string name = 2;</code>
       */
      public Builder clearName() {

        name_ = getDefaultInstance().getName();
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 姓名
       * </pre>
       *
       * <code>string name = 2;</code>
       */
      public Builder setNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);

        name_ = value;
        onChanged();
        return this;
      }

      private long time_ ;
      /**
       * <pre>
       * 时间戳
       * </pre>
       *
       * <code>int64 time = 3;</code>
       */
      public long getTime() {
        return time_;
      }
      /**
       * <pre>
       * 时间戳
       * </pre>
       *
       * <code>int64 time = 3;</code>
       */
      public Builder setTime(long value) {

        time_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 时间戳
       * </pre>
       *
       * <code>int64 time = 3;</code>
       */
      public Builder clearTime() {

        time_ = 0L;
        onChanged();
        return this;
      }

      private int gender_ = 0;
      /**
       * <pre>
       * 性别
       * </pre>
       *
       * <code>.BaseInfoMsg.Gender gender = 4;</code>
       */
      public int getGenderValue() {
        return gender_;
      }
      /**
       * <pre>
       * 性别
       * </pre>
       *
       * <code>.BaseInfoMsg.Gender gender = 4;</code>
       */
      public Builder setGenderValue(int value) {
        gender_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 性别
       * </pre>
       *
       * <code>.BaseInfoMsg.Gender gender = 4;</code>
       */
      public me.vicasong.swagger.docgen.protocol.TestProtos.BaseInfoMsg.Gender getGender() {
        me.vicasong.swagger.docgen.protocol.TestProtos.BaseInfoMsg.Gender result = me.vicasong.swagger.docgen.protocol.TestProtos.BaseInfoMsg.Gender.valueOf(gender_);
        return result == null ? me.vicasong.swagger.docgen.protocol.TestProtos.BaseInfoMsg.Gender.UNRECOGNIZED : result;
      }
      /**
       * <pre>
       * 性别
       * </pre>
       *
       * <code>.BaseInfoMsg.Gender gender = 4;</code>
       */
      public Builder setGender(me.vicasong.swagger.docgen.protocol.TestProtos.BaseInfoMsg.Gender value) {
        if (value == null) {
          throw new NullPointerException();
        }

        gender_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 性别
       * </pre>
       *
       * <code>.BaseInfoMsg.Gender gender = 4;</code>
       */
      public Builder clearGender() {

        gender_ = 0;
        onChanged();
        return this;
      }

      private Object address_ = "";
      /**
       * <pre>
       * 地址
       * </pre>
       *
       * <code>string address = 5;</code>
       */
      public String getAddress() {
        Object ref = address_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          address_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <pre>
       * 地址
       * </pre>
       *
       * <code>string address = 5;</code>
       */
      public com.google.protobuf.ByteString
          getAddressBytes() {
        Object ref = address_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b =
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          address_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       * 地址
       * </pre>
       *
       * <code>string address = 5;</code>
       */
      public Builder setAddress(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }

        address_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 地址
       * </pre>
       *
       * <code>string address = 5;</code>
       */
      public Builder clearAddress() {

        address_ = getDefaultInstance().getAddress();
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 地址
       * </pre>
       *
       * <code>string address = 5;</code>
       */
      public Builder setAddressBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);

        address_ = value;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:BaseInfoMsg)
    }

    // @@protoc_insertion_point(class_scope:BaseInfoMsg)
    private static final me.vicasong.swagger.docgen.protocol.TestProtos.BaseInfoMsg DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new me.vicasong.swagger.docgen.protocol.TestProtos.BaseInfoMsg();
    }

    public static me.vicasong.swagger.docgen.protocol.TestProtos.BaseInfoMsg getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<BaseInfoMsg>
        PARSER = new com.google.protobuf.AbstractParser<BaseInfoMsg>() {
      public BaseInfoMsg parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new BaseInfoMsg(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<BaseInfoMsg> parser() {
      return PARSER;
    }

    @Override
    public com.google.protobuf.Parser<BaseInfoMsg> getParserForType() {
      return PARSER;
    }

    public me.vicasong.swagger.docgen.protocol.TestProtos.BaseInfoMsg getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface StudentMsgOrBuilder extends
      // @@protoc_insertion_point(interface_extends:StudentMsg)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     * 基础信息
     * </pre>
     *
     * <code>.BaseInfoMsg info = 1;</code>
     */
    boolean hasInfo();
    /**
     * <pre>
     * 基础信息
     * </pre>
     *
     * <code>.BaseInfoMsg info = 1;</code>
     */
    me.vicasong.swagger.docgen.protocol.TestProtos.BaseInfoMsg getInfo();
    /**
     * <pre>
     * 基础信息
     * </pre>
     *
     * <code>.BaseInfoMsg info = 1;</code>
     */
    me.vicasong.swagger.docgen.protocol.TestProtos.BaseInfoMsgOrBuilder getInfoOrBuilder();

    /**
     * <pre>
     * 班级
     * </pre>
     *
     * <code>int32 class = 2;</code>
     */
    int getClass_();

    /**
     * <pre>
     * 累计考试分数列表
     * </pre>
     *
     * <code>repeated int64 scores = 3;</code>
     */
    java.util.List<Long> getScoresList();
    /**
     * <pre>
     * 累计考试分数列表
     * </pre>
     *
     * <code>repeated int64 scores = 3;</code>
     */
    int getScoresCount();
    /**
     * <pre>
     * 累计考试分数列表
     * </pre>
     *
     * <code>repeated int64 scores = 3;</code>
     */
    long getScores(int index);

    /**
     * <pre>
     * 记过
     * </pre>
     *
     * <code>map&lt;string, string&gt; events = 4;</code>
     */
    int getEventsCount();
    /**
     * <pre>
     * 记过
     * </pre>
     *
     * <code>map&lt;string, string&gt; events = 4;</code>
     */
    boolean containsEvents(
            String key);
    /**
     * Use {@link #getEventsMap()} instead.
     */
    @Deprecated
    java.util.Map<String, String>
    getEvents();
    /**
     * <pre>
     * 记过
     * </pre>
     *
     * <code>map&lt;string, string&gt; events = 4;</code>
     */
    java.util.Map<String, String>
    getEventsMap();
    /**
     * <pre>
     * 记过
     * </pre>
     *
     * <code>map&lt;string, string&gt; events = 4;</code>
     */

    String getEventsOrDefault(
            String key,
            String defaultValue);
    /**
     * <pre>
     * 记过
     * </pre>
     *
     * <code>map&lt;string, string&gt; events = 4;</code>
     */

    String getEventsOrThrow(
            String key);
  }
  /**
   * <pre>
   * 变更信息
   * </pre>
   *
   * Protobuf type {@code StudentMsg}
   */
  public  static final class StudentMsg extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:StudentMsg)
      StudentMsgOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use StudentMsg.newBuilder() to construct.
    private StudentMsg(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private StudentMsg() {
      class__ = 0;
      scores_ = java.util.Collections.emptyList();
    }

    @Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private StudentMsg(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              me.vicasong.swagger.docgen.protocol.TestProtos.BaseInfoMsg.Builder subBuilder = null;
              if (info_ != null) {
                subBuilder = info_.toBuilder();
              }
              info_ = input.readMessage(me.vicasong.swagger.docgen.protocol.TestProtos.BaseInfoMsg.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(info_);
                info_ = subBuilder.buildPartial();
              }

              break;
            }
            case 16: {

              class__ = input.readInt32();
              break;
            }
            case 24: {
              if (!((mutable_bitField0_ & 0x00000004) == 0x00000004)) {
                scores_ = new java.util.ArrayList<Long>();
                mutable_bitField0_ |= 0x00000004;
              }
              scores_.add(input.readInt64());
              break;
            }
            case 26: {
              int length = input.readRawVarint32();
              int limit = input.pushLimit(length);
              if (!((mutable_bitField0_ & 0x00000004) == 0x00000004) && input.getBytesUntilLimit() > 0) {
                scores_ = new java.util.ArrayList<Long>();
                mutable_bitField0_ |= 0x00000004;
              }
              while (input.getBytesUntilLimit() > 0) {
                scores_.add(input.readInt64());
              }
              input.popLimit(limit);
              break;
            }
            case 34: {
              if (!((mutable_bitField0_ & 0x00000008) == 0x00000008)) {
                events_ = com.google.protobuf.MapField.newMapField(
                    EventsDefaultEntryHolder.defaultEntry);
                mutable_bitField0_ |= 0x00000008;
              }
              com.google.protobuf.MapEntry<String, String>
              events__ = input.readMessage(
                  EventsDefaultEntryHolder.defaultEntry.getParserForType(), extensionRegistry);
              events_.getMutableMap().put(
                  events__.getKey(), events__.getValue());
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000004) == 0x00000004)) {
          scores_ = java.util.Collections.unmodifiableList(scores_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return me.vicasong.swagger.docgen.protocol.TestProtos.internal_static_StudentMsg_descriptor;
    }

    @SuppressWarnings({"rawtypes"})
    protected com.google.protobuf.MapField internalGetMapField(
        int number) {
      switch (number) {
        case 4:
          return internalGetEvents();
        default:
          throw new RuntimeException(
              "Invalid map field number: " + number);
      }
    }
    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return me.vicasong.swagger.docgen.protocol.TestProtos.internal_static_StudentMsg_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              me.vicasong.swagger.docgen.protocol.TestProtos.StudentMsg.class, me.vicasong.swagger.docgen.protocol.TestProtos.StudentMsg.Builder.class);
    }

    private int bitField0_;
    public static final int INFO_FIELD_NUMBER = 1;
    private me.vicasong.swagger.docgen.protocol.TestProtos.BaseInfoMsg info_;
    /**
     * <pre>
     * 基础信息
     * </pre>
     *
     * <code>.BaseInfoMsg info = 1;</code>
     */
    public boolean hasInfo() {
      return info_ != null;
    }
    /**
     * <pre>
     * 基础信息
     * </pre>
     *
     * <code>.BaseInfoMsg info = 1;</code>
     */
    public me.vicasong.swagger.docgen.protocol.TestProtos.BaseInfoMsg getInfo() {
      return info_ == null ? me.vicasong.swagger.docgen.protocol.TestProtos.BaseInfoMsg.getDefaultInstance() : info_;
    }
    /**
     * <pre>
     * 基础信息
     * </pre>
     *
     * <code>.BaseInfoMsg info = 1;</code>
     */
    public me.vicasong.swagger.docgen.protocol.TestProtos.BaseInfoMsgOrBuilder getInfoOrBuilder() {
      return getInfo();
    }

    public static final int CLASS_FIELD_NUMBER = 2;
    private int class__;
    /**
     * <pre>
     * 班级
     * </pre>
     *
     * <code>int32 class = 2;</code>
     */
    public int getClass_() {
      return class__;
    }

    public static final int SCORES_FIELD_NUMBER = 3;
    private java.util.List<Long> scores_;
    /**
     * <pre>
     * 累计考试分数列表
     * </pre>
     *
     * <code>repeated int64 scores = 3;</code>
     */
    public java.util.List<Long>
        getScoresList() {
      return scores_;
    }
    /**
     * <pre>
     * 累计考试分数列表
     * </pre>
     *
     * <code>repeated int64 scores = 3;</code>
     */
    public int getScoresCount() {
      return scores_.size();
    }
    /**
     * <pre>
     * 累计考试分数列表
     * </pre>
     *
     * <code>repeated int64 scores = 3;</code>
     */
    public long getScores(int index) {
      return scores_.get(index);
    }
    private int scoresMemoizedSerializedSize = -1;

    public static final int EVENTS_FIELD_NUMBER = 4;
    private static final class EventsDefaultEntryHolder {
      static final com.google.protobuf.MapEntry<
          String, String> defaultEntry =
              com.google.protobuf.MapEntry
              .<String, String>newDefaultInstance(
                  me.vicasong.swagger.docgen.protocol.TestProtos.internal_static_StudentMsg_EventsEntry_descriptor,
                  com.google.protobuf.WireFormat.FieldType.STRING,
                  "",
                  com.google.protobuf.WireFormat.FieldType.STRING,
                  "");
    }
    private com.google.protobuf.MapField<
        String, String> events_;
    private com.google.protobuf.MapField<String, String>
    internalGetEvents() {
      if (events_ == null) {
        return com.google.protobuf.MapField.emptyMapField(
            EventsDefaultEntryHolder.defaultEntry);
      }
      return events_;
    }

    public int getEventsCount() {
      return internalGetEvents().getMap().size();
    }
    /**
     * <pre>
     * 记过
     * </pre>
     *
     * <code>map&lt;string, string&gt; events = 4;</code>
     */

    public boolean containsEvents(
        String key) {
      if (key == null) { throw new NullPointerException(); }
      return internalGetEvents().getMap().containsKey(key);
    }
    /**
     * Use {@link #getEventsMap()} instead.
     */
    @Deprecated
    public java.util.Map<String, String> getEvents() {
      return getEventsMap();
    }
    /**
     * <pre>
     * 记过
     * </pre>
     *
     * <code>map&lt;string, string&gt; events = 4;</code>
     */

    public java.util.Map<String, String> getEventsMap() {
      return internalGetEvents().getMap();
    }
    /**
     * <pre>
     * 记过
     * </pre>
     *
     * <code>map&lt;string, string&gt; events = 4;</code>
     */

    public String getEventsOrDefault(
        String key,
        String defaultValue) {
      if (key == null) { throw new NullPointerException(); }
      java.util.Map<String, String> map =
          internalGetEvents().getMap();
      return map.containsKey(key) ? map.get(key) : defaultValue;
    }
    /**
     * <pre>
     * 记过
     * </pre>
     *
     * <code>map&lt;string, string&gt; events = 4;</code>
     */

    public String getEventsOrThrow(
        String key) {
      if (key == null) { throw new NullPointerException(); }
      java.util.Map<String, String> map =
          internalGetEvents().getMap();
      if (!map.containsKey(key)) {
        throw new IllegalArgumentException();
      }
      return map.get(key);
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (info_ != null) {
        output.writeMessage(1, getInfo());
      }
      if (class__ != 0) {
        output.writeInt32(2, class__);
      }
      if (getScoresList().size() > 0) {
        output.writeUInt32NoTag(26);
        output.writeUInt32NoTag(scoresMemoizedSerializedSize);
      }
      for (int i = 0; i < scores_.size(); i++) {
        output.writeInt64NoTag(scores_.get(i));
      }
      com.google.protobuf.GeneratedMessageV3
        .serializeStringMapTo(
          output,
          internalGetEvents(),
          EventsDefaultEntryHolder.defaultEntry,
          4);
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (info_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, getInfo());
      }
      if (class__ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, class__);
      }
      {
        int dataSize = 0;
        for (int i = 0; i < scores_.size(); i++) {
          dataSize += com.google.protobuf.CodedOutputStream
            .computeInt64SizeNoTag(scores_.get(i));
        }
        size += dataSize;
        if (!getScoresList().isEmpty()) {
          size += 1;
          size += com.google.protobuf.CodedOutputStream
              .computeInt32SizeNoTag(dataSize);
        }
        scoresMemoizedSerializedSize = dataSize;
      }
      for (java.util.Map.Entry<String, String> entry
           : internalGetEvents().getMap().entrySet()) {
        com.google.protobuf.MapEntry<String, String>
        events__ = EventsDefaultEntryHolder.defaultEntry.newBuilderForType()
            .setKey(entry.getKey())
            .setValue(entry.getValue())
            .build();
        size += com.google.protobuf.CodedOutputStream
            .computeMessageSize(4, events__);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @Override
    public boolean equals(final Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof me.vicasong.swagger.docgen.protocol.TestProtos.StudentMsg)) {
        return super.equals(obj);
      }
      me.vicasong.swagger.docgen.protocol.TestProtos.StudentMsg other = (me.vicasong.swagger.docgen.protocol.TestProtos.StudentMsg) obj;

      boolean result = true;
      result = result && (hasInfo() == other.hasInfo());
      if (hasInfo()) {
        result = result && getInfo()
            .equals(other.getInfo());
      }
      result = result && (getClass_()
          == other.getClass_());
      result = result && getScoresList()
          .equals(other.getScoresList());
      result = result && internalGetEvents().equals(
          other.internalGetEvents());
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasInfo()) {
        hash = (37 * hash) + INFO_FIELD_NUMBER;
        hash = (53 * hash) + getInfo().hashCode();
      }
      hash = (37 * hash) + CLASS_FIELD_NUMBER;
      hash = (53 * hash) + getClass_();
      if (getScoresCount() > 0) {
        hash = (37 * hash) + SCORES_FIELD_NUMBER;
        hash = (53 * hash) + getScoresList().hashCode();
      }
      if (!internalGetEvents().getMap().isEmpty()) {
        hash = (37 * hash) + EVENTS_FIELD_NUMBER;
        hash = (53 * hash) + internalGetEvents().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static me.vicasong.swagger.docgen.protocol.TestProtos.StudentMsg parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static me.vicasong.swagger.docgen.protocol.TestProtos.StudentMsg parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static me.vicasong.swagger.docgen.protocol.TestProtos.StudentMsg parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static me.vicasong.swagger.docgen.protocol.TestProtos.StudentMsg parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static me.vicasong.swagger.docgen.protocol.TestProtos.StudentMsg parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static me.vicasong.swagger.docgen.protocol.TestProtos.StudentMsg parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static me.vicasong.swagger.docgen.protocol.TestProtos.StudentMsg parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static me.vicasong.swagger.docgen.protocol.TestProtos.StudentMsg parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static me.vicasong.swagger.docgen.protocol.TestProtos.StudentMsg parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static me.vicasong.swagger.docgen.protocol.TestProtos.StudentMsg parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static me.vicasong.swagger.docgen.protocol.TestProtos.StudentMsg parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static me.vicasong.swagger.docgen.protocol.TestProtos.StudentMsg parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(me.vicasong.swagger.docgen.protocol.TestProtos.StudentMsg prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @Override
    protected Builder newBuilderForType(
        BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * <pre>
     * 变更信息
     * </pre>
     *
     * Protobuf type {@code StudentMsg}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:StudentMsg)
        me.vicasong.swagger.docgen.protocol.TestProtos.StudentMsgOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return me.vicasong.swagger.docgen.protocol.TestProtos.internal_static_StudentMsg_descriptor;
      }

      @SuppressWarnings({"rawtypes"})
      protected com.google.protobuf.MapField internalGetMapField(
          int number) {
        switch (number) {
          case 4:
            return internalGetEvents();
          default:
            throw new RuntimeException(
                "Invalid map field number: " + number);
        }
      }
      @SuppressWarnings({"rawtypes"})
      protected com.google.protobuf.MapField internalGetMutableMapField(
          int number) {
        switch (number) {
          case 4:
            return internalGetMutableEvents();
          default:
            throw new RuntimeException(
                "Invalid map field number: " + number);
        }
      }
      protected FieldAccessorTable
          internalGetFieldAccessorTable() {
        return me.vicasong.swagger.docgen.protocol.TestProtos.internal_static_StudentMsg_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                me.vicasong.swagger.docgen.protocol.TestProtos.StudentMsg.class, me.vicasong.swagger.docgen.protocol.TestProtos.StudentMsg.Builder.class);
      }

      // Construct using me.vicasong.swagger.docgen.protocol.TestProtos.StudentMsg.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        if (infoBuilder_ == null) {
          info_ = null;
        } else {
          info_ = null;
          infoBuilder_ = null;
        }
        class__ = 0;

        scores_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000004);
        internalGetMutableEvents().clear();
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return me.vicasong.swagger.docgen.protocol.TestProtos.internal_static_StudentMsg_descriptor;
      }

      public me.vicasong.swagger.docgen.protocol.TestProtos.StudentMsg getDefaultInstanceForType() {
        return me.vicasong.swagger.docgen.protocol.TestProtos.StudentMsg.getDefaultInstance();
      }

      public me.vicasong.swagger.docgen.protocol.TestProtos.StudentMsg build() {
        me.vicasong.swagger.docgen.protocol.TestProtos.StudentMsg result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public me.vicasong.swagger.docgen.protocol.TestProtos.StudentMsg buildPartial() {
        me.vicasong.swagger.docgen.protocol.TestProtos.StudentMsg result = new me.vicasong.swagger.docgen.protocol.TestProtos.StudentMsg(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (infoBuilder_ == null) {
          result.info_ = info_;
        } else {
          result.info_ = infoBuilder_.build();
        }
        result.class__ = class__;
        if (((bitField0_ & 0x00000004) == 0x00000004)) {
          scores_ = java.util.Collections.unmodifiableList(scores_);
          bitField0_ = (bitField0_ & ~0x00000004);
        }
        result.scores_ = scores_;
        result.events_ = internalGetEvents();
        result.events_.makeImmutable();
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof me.vicasong.swagger.docgen.protocol.TestProtos.StudentMsg) {
          return mergeFrom((me.vicasong.swagger.docgen.protocol.TestProtos.StudentMsg)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(me.vicasong.swagger.docgen.protocol.TestProtos.StudentMsg other) {
        if (other == me.vicasong.swagger.docgen.protocol.TestProtos.StudentMsg.getDefaultInstance()) return this;
        if (other.hasInfo()) {
          mergeInfo(other.getInfo());
        }
        if (other.getClass_() != 0) {
          setClass_(other.getClass_());
        }
        if (!other.scores_.isEmpty()) {
          if (scores_.isEmpty()) {
            scores_ = other.scores_;
            bitField0_ = (bitField0_ & ~0x00000004);
          } else {
            ensureScoresIsMutable();
            scores_.addAll(other.scores_);
          }
          onChanged();
        }
        internalGetMutableEvents().mergeFrom(
            other.internalGetEvents());
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        me.vicasong.swagger.docgen.protocol.TestProtos.StudentMsg parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (me.vicasong.swagger.docgen.protocol.TestProtos.StudentMsg) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private me.vicasong.swagger.docgen.protocol.TestProtos.BaseInfoMsg info_ = null;
      private com.google.protobuf.SingleFieldBuilderV3<
          BaseInfoMsg, BaseInfoMsg.Builder, BaseInfoMsgOrBuilder> infoBuilder_;
      /**
       * <pre>
       * 基础信息
       * </pre>
       *
       * <code>.BaseInfoMsg info = 1;</code>
       */
      public boolean hasInfo() {
        return infoBuilder_ != null || info_ != null;
      }
      /**
       * <pre>
       * 基础信息
       * </pre>
       *
       * <code>.BaseInfoMsg info = 1;</code>
       */
      public me.vicasong.swagger.docgen.protocol.TestProtos.BaseInfoMsg getInfo() {
        if (infoBuilder_ == null) {
          return info_ == null ? me.vicasong.swagger.docgen.protocol.TestProtos.BaseInfoMsg.getDefaultInstance() : info_;
        } else {
          return infoBuilder_.getMessage();
        }
      }
      /**
       * <pre>
       * 基础信息
       * </pre>
       *
       * <code>.BaseInfoMsg info = 1;</code>
       */
      public Builder setInfo(me.vicasong.swagger.docgen.protocol.TestProtos.BaseInfoMsg value) {
        if (infoBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          info_ = value;
          onChanged();
        } else {
          infoBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <pre>
       * 基础信息
       * </pre>
       *
       * <code>.BaseInfoMsg info = 1;</code>
       */
      public Builder setInfo(
          me.vicasong.swagger.docgen.protocol.TestProtos.BaseInfoMsg.Builder builderForValue) {
        if (infoBuilder_ == null) {
          info_ = builderForValue.build();
          onChanged();
        } else {
          infoBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <pre>
       * 基础信息
       * </pre>
       *
       * <code>.BaseInfoMsg info = 1;</code>
       */
      public Builder mergeInfo(me.vicasong.swagger.docgen.protocol.TestProtos.BaseInfoMsg value) {
        if (infoBuilder_ == null) {
          if (info_ != null) {
            info_ =
              me.vicasong.swagger.docgen.protocol.TestProtos.BaseInfoMsg.newBuilder(info_).mergeFrom(value).buildPartial();
          } else {
            info_ = value;
          }
          onChanged();
        } else {
          infoBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <pre>
       * 基础信息
       * </pre>
       *
       * <code>.BaseInfoMsg info = 1;</code>
       */
      public Builder clearInfo() {
        if (infoBuilder_ == null) {
          info_ = null;
          onChanged();
        } else {
          info_ = null;
          infoBuilder_ = null;
        }

        return this;
      }
      /**
       * <pre>
       * 基础信息
       * </pre>
       *
       * <code>.BaseInfoMsg info = 1;</code>
       */
      public me.vicasong.swagger.docgen.protocol.TestProtos.BaseInfoMsg.Builder getInfoBuilder() {

        onChanged();
        return getInfoFieldBuilder().getBuilder();
      }
      /**
       * <pre>
       * 基础信息
       * </pre>
       *
       * <code>.BaseInfoMsg info = 1;</code>
       */
      public me.vicasong.swagger.docgen.protocol.TestProtos.BaseInfoMsgOrBuilder getInfoOrBuilder() {
        if (infoBuilder_ != null) {
          return infoBuilder_.getMessageOrBuilder();
        } else {
          return info_ == null ?
              me.vicasong.swagger.docgen.protocol.TestProtos.BaseInfoMsg.getDefaultInstance() : info_;
        }
      }
      /**
       * <pre>
       * 基础信息
       * </pre>
       *
       * <code>.BaseInfoMsg info = 1;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          BaseInfoMsg, BaseInfoMsg.Builder, BaseInfoMsgOrBuilder>
          getInfoFieldBuilder() {
        if (infoBuilder_ == null) {
          infoBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              BaseInfoMsg, BaseInfoMsg.Builder, BaseInfoMsgOrBuilder>(
                  getInfo(),
                  getParentForChildren(),
                  isClean());
          info_ = null;
        }
        return infoBuilder_;
      }

      private int class__ ;
      /**
       * <pre>
       * 班级
       * </pre>
       *
       * <code>int32 class = 2;</code>
       */
      public int getClass_() {
        return class__;
      }
      /**
       * <pre>
       * 班级
       * </pre>
       *
       * <code>int32 class = 2;</code>
       */
      public Builder setClass_(int value) {

        class__ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 班级
       * </pre>
       *
       * <code>int32 class = 2;</code>
       */
      public Builder clearClass_() {

        class__ = 0;
        onChanged();
        return this;
      }

      private java.util.List<Long> scores_ = java.util.Collections.emptyList();
      private void ensureScoresIsMutable() {
        if (!((bitField0_ & 0x00000004) == 0x00000004)) {
          scores_ = new java.util.ArrayList<Long>(scores_);
          bitField0_ |= 0x00000004;
         }
      }
      /**
       * <pre>
       * 累计考试分数列表
       * </pre>
       *
       * <code>repeated int64 scores = 3;</code>
       */
      public java.util.List<Long>
          getScoresList() {
        return java.util.Collections.unmodifiableList(scores_);
      }
      /**
       * <pre>
       * 累计考试分数列表
       * </pre>
       *
       * <code>repeated int64 scores = 3;</code>
       */
      public int getScoresCount() {
        return scores_.size();
      }
      /**
       * <pre>
       * 累计考试分数列表
       * </pre>
       *
       * <code>repeated int64 scores = 3;</code>
       */
      public long getScores(int index) {
        return scores_.get(index);
      }
      /**
       * <pre>
       * 累计考试分数列表
       * </pre>
       *
       * <code>repeated int64 scores = 3;</code>
       */
      public Builder setScores(
          int index, long value) {
        ensureScoresIsMutable();
        scores_.set(index, value);
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 累计考试分数列表
       * </pre>
       *
       * <code>repeated int64 scores = 3;</code>
       */
      public Builder addScores(long value) {
        ensureScoresIsMutable();
        scores_.add(value);
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 累计考试分数列表
       * </pre>
       *
       * <code>repeated int64 scores = 3;</code>
       */
      public Builder addAllScores(
          Iterable<? extends Long> values) {
        ensureScoresIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, scores_);
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 累计考试分数列表
       * </pre>
       *
       * <code>repeated int64 scores = 3;</code>
       */
      public Builder clearScores() {
        scores_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000004);
        onChanged();
        return this;
      }

      private com.google.protobuf.MapField<
          String, String> events_;
      private com.google.protobuf.MapField<String, String>
      internalGetEvents() {
        if (events_ == null) {
          return com.google.protobuf.MapField.emptyMapField(
              EventsDefaultEntryHolder.defaultEntry);
        }
        return events_;
      }
      private com.google.protobuf.MapField<String, String>
      internalGetMutableEvents() {
        onChanged();;
        if (events_ == null) {
          events_ = com.google.protobuf.MapField.newMapField(
              EventsDefaultEntryHolder.defaultEntry);
        }
        if (!events_.isMutable()) {
          events_ = events_.copy();
        }
        return events_;
      }

      public int getEventsCount() {
        return internalGetEvents().getMap().size();
      }
      /**
       * <pre>
       * 记过
       * </pre>
       *
       * <code>map&lt;string, string&gt; events = 4;</code>
       */

      public boolean containsEvents(
          String key) {
        if (key == null) { throw new NullPointerException(); }
        return internalGetEvents().getMap().containsKey(key);
      }
      /**
       * Use {@link #getEventsMap()} instead.
       */
      @Deprecated
      public java.util.Map<String, String> getEvents() {
        return getEventsMap();
      }
      /**
       * <pre>
       * 记过
       * </pre>
       *
       * <code>map&lt;string, string&gt; events = 4;</code>
       */

      public java.util.Map<String, String> getEventsMap() {
        return internalGetEvents().getMap();
      }
      /**
       * <pre>
       * 记过
       * </pre>
       *
       * <code>map&lt;string, string&gt; events = 4;</code>
       */

      public String getEventsOrDefault(
          String key,
          String defaultValue) {
        if (key == null) { throw new NullPointerException(); }
        java.util.Map<String, String> map =
            internalGetEvents().getMap();
        return map.containsKey(key) ? map.get(key) : defaultValue;
      }
      /**
       * <pre>
       * 记过
       * </pre>
       *
       * <code>map&lt;string, string&gt; events = 4;</code>
       */

      public String getEventsOrThrow(
          String key) {
        if (key == null) { throw new NullPointerException(); }
        java.util.Map<String, String> map =
            internalGetEvents().getMap();
        if (!map.containsKey(key)) {
          throw new IllegalArgumentException();
        }
        return map.get(key);
      }

      public Builder clearEvents() {
        internalGetMutableEvents().getMutableMap()
            .clear();
        return this;
      }
      /**
       * <pre>
       * 记过
       * </pre>
       *
       * <code>map&lt;string, string&gt; events = 4;</code>
       */

      public Builder removeEvents(
          String key) {
        if (key == null) { throw new NullPointerException(); }
        internalGetMutableEvents().getMutableMap()
            .remove(key);
        return this;
      }
      /**
       * Use alternate mutation accessors instead.
       */
      @Deprecated
      public java.util.Map<String, String>
      getMutableEvents() {
        return internalGetMutableEvents().getMutableMap();
      }
      /**
       * <pre>
       * 记过
       * </pre>
       *
       * <code>map&lt;string, string&gt; events = 4;</code>
       */
      public Builder putEvents(
          String key,
          String value) {
        if (key == null) { throw new NullPointerException(); }
        if (value == null) { throw new NullPointerException(); }
        internalGetMutableEvents().getMutableMap()
            .put(key, value);
        return this;
      }
      /**
       * <pre>
       * 记过
       * </pre>
       *
       * <code>map&lt;string, string&gt; events = 4;</code>
       */

      public Builder putAllEvents(
          java.util.Map<String, String> values) {
        internalGetMutableEvents().getMutableMap()
            .putAll(values);
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:StudentMsg)
    }

    // @@protoc_insertion_point(class_scope:StudentMsg)
    private static final me.vicasong.swagger.docgen.protocol.TestProtos.StudentMsg DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new me.vicasong.swagger.docgen.protocol.TestProtos.StudentMsg();
    }

    public static me.vicasong.swagger.docgen.protocol.TestProtos.StudentMsg getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<StudentMsg>
        PARSER = new com.google.protobuf.AbstractParser<StudentMsg>() {
      public StudentMsg parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new StudentMsg(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<StudentMsg> parser() {
      return PARSER;
    }

    @Override
    public com.google.protobuf.Parser<StudentMsg> getParserForType() {
      return PARSER;
    }

    public me.vicasong.swagger.docgen.protocol.TestProtos.StudentMsg getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_BaseInfoMsg_descriptor;
  private static final
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_BaseInfoMsg_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_StudentMsg_descriptor;
  private static final
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_StudentMsg_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_StudentMsg_EventsEntry_descriptor;
  private static final
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_StudentMsg_EventsEntry_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    String[] descriptorData = {
      "\n\020proto_test.proto\"\213\001\n\013BaseInfoMsg\022\n\n\002id" +
      "\030\001 \001(\005\022\014\n\004name\030\002 \001(\t\022\014\n\004time\030\003 \001(\003\022#\n\006ge" +
      "nder\030\004 \001(\0162\023.BaseInfoMsg.Gender\022\017\n\007addre" +
      "ss\030\005 \001(\t\"\036\n\006Gender\022\010\n\004MALE\020\000\022\n\n\006FEMALE\020\001" +
      "\"\237\001\n\nStudentMsg\022\032\n\004info\030\001 \001(\0132\014.BaseInfo" +
      "Msg\022\r\n\005class\030\002 \001(\005\022\016\n\006scores\030\003 \003(\003\022\'\n\006ev" +
      "ents\030\004 \003(\0132\027.StudentMsg.EventsEntry\032-\n\013E" +
      "ventsEntry\022\013\n\003key\030\001 \001(\t\022\r\n\005value\030\002 \001(\t:\002" +
      "8\001B1\n#me.vicasong.swagger.docgen.protoco" +
      "lB\nTestProtosb\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_BaseInfoMsg_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_BaseInfoMsg_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_BaseInfoMsg_descriptor,
        new String[] { "Id", "Name", "Time", "Gender", "Address", });
    internal_static_StudentMsg_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_StudentMsg_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_StudentMsg_descriptor,
        new String[] { "Info", "Class_", "Scores", "Events", });
    internal_static_StudentMsg_EventsEntry_descriptor =
      internal_static_StudentMsg_descriptor.getNestedTypes().get(0);
    internal_static_StudentMsg_EventsEntry_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_StudentMsg_EventsEntry_descriptor,
        new String[] { "Key", "Value", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
